import { BUSINESS_CONFIG, validateBusinessConfig } from "./config/business";
import { OFFICIAL_TARIFF_CONFIG } from "./config/tarifas";

validateBusinessConfig(BUSINESS_CONFIG);

export const CONTACT = {
  phoneDisplay: BUSINESS_CONFIG.phoneDisplay,
  phoneHref: BUSINESS_CONFIG.phoneHref,
  whatsapp: BUSINESS_CONFIG.whatsapp,
  address: BUSINESS_CONFIG.publicAddress,
  googleProfile: BUSINESS_CONFIG.googleProfile,
  place: BUSINESS_CONFIG.publicPlace,
  license: BUSINESS_CONFIG.license,
};

export const LEGAL = {
  owner: "Charaf Eddine El Hatri Sbai",
  taxId: "60535727A",
  address: "Calatayud, Zaragoza",
  businessName: "Taxi Ayud",
};

export const RATES = {
  dayRate: OFFICIAL_TARIFF_CONFIG.interurban.day.pricePerKm,
  nightRate: OFFICIAL_TARIFF_CONFIG.interurban.nightHoliday.pricePerKm,
  dayWaitRate: OFFICIAL_TARIFF_CONFIG.interurban.day.waitPerHour,
  nightWaitRate: OFFICIAL_TARIFF_CONFIG.interurban.nightHoliday.waitPerHour,
  returnFactor: OFFICIAL_TARIFF_CONFIG.calculation.returnFactor,
  officialNotice: OFFICIAL_TARIFF_CONFIG.sourceLabel,
};

export const GOOGLE_REVIEWS = {
  rating: "5/5",
  count: "10 reseñas",
  items: [
    {
      author: "Raquel C",
      text: "Ante la dificultad de encontrar taxi en Calatayud, una suerte dar con ellos. Los necesité dos veces y fui con el mismo taxista, muy amable y puntual. El taxi perfecto, muy limpio y cómodo. Totalmente recomendable.",
      time: "Reseña destacada",
      rating: 5,
      url: "https://share.google/vVhE9TRxVGqUYTwKp",
    },
    {
      author: "Darlene Cuevas",
      text: "I can't recommend this taxi service highly enough! I was stranded at the Mercadona near the station...",
      time: "Reseña reciente",
      rating: 5,
    },
    {
      author: "VIRAL VIDEOS #1",
      text: "Excelente servicio de taxi en Calatayud. Puntual, amable y muy profesional; el coche estaba limpio y el trayecto fue cómodo y seguro.",
      time: "Hace una semana",
      rating: 5,
    },
    {
      author: "ImNotAlejandro W",
      text: "Servicio premium, educación, puntualidad, el vehículo en excelente estado 10/10",
      time: "Hace 2 semanas",
      rating: 5,
    },
    {
      author: "hakim msellek",
      text: "Excelente servicio",
      time: "Hace 2 semanas",
      rating: 5,
    },
    { author: "Ady Adita", text: "El mejor taxi" },
    { author: "Ronmel Manuel", text: "Excelente servicio" },
    { author: "Jorge D", text: "Puntual y coche cómodo" },
  ],
};

export type Tariff = {
  km: number;
};

export const TARIFAS: Record<string, Tariff> = {
  "ABANTO": { km: 38 },
  "ACERED": { km: 27 },
  "AGREDA": { km: 100 },
  "AINZON": { km: 80 },
  "ALAGON": { km: 72 },
  "ALARBA": { km: 21 },
  "ALCALA DEL MONCAYO": { km: 101.5 },
  "ALCANIZ": { km: 180 },
  "ALCONCHEL": { km: 70 },
  "ALFAJARIN": { km: 107 },
  "ALFAMEN": { km: 50 },
  "ALGAR DE MESA": { km: 63 },
  "ALHAMA DE ARAGON": { km: 30 },
  "ALMAZAN": { km: 90 },
  "ALMONACID DE LA SIERRA": { km: 50 },
  "ALPARTIR": { km: 46 },
  "ALUENDA": { km: 16 },
  "ALDEHUELA DE LIESTOS": { km: 53 },
  "ANINON": { km: 18 },
  "ARANDA DEL MONCAYO": { km: 51 },
  "ARANDIGA": { km: 35 },
  "ARCOS DE JALON": { km: 70 },
  "ARIZA": { km: 45 },
  "ATECA": { km: 15 },
  "BARCELONA": { km: 400 },
  "BELCHITE": { km: 105 },
  "BELMONTE": { km: 12.5 },
  "BENASQUE": { km: 300 },
  "BERDEJO": { km: 47 },
  "BIJUESCA": { km: 50 },
  "BINEFAR": { km: 241 },
  "BORDALBA": { km: 53 },
  "BORJA": { km: 85 },
  "BREA DE ARAGON": { km: 40 },
  "BUBIERCA": { km: 23 },
  "BUJARALOZ": { km: 155 },
  "BURBAGUENA": { km: 53 },
  "BURGOS": { km: 236 },
  "BURGO DE OSMA": { km: 150 },
  "CABOLAFUENTE": { km: 59 },
  "CALAMOCHA": { km: 70 },
  "CALATORAO": { km: 42 },
  "CALCENA": { km: 70 },
  "CALMARZA": { km: 50 },
  "CAMPILLO": { km: 43 },
  "CARENAS": { km: 25 },
  "CARINENA": { km: 58 },
  "CASPE": { km: 195 },
  "CASTEJON DE ALARBA": { km: 27 },
  "CASTEJON DE LAS ARMAS": { km: 20 },
  "CETINA": { km: 36 },
  "CERVERA DE LA CANADA": { km: 16 },
  "CIMBALLA": { km: 45 },
  "CLARES": { km: 35 },
  "CODOS": { km: 33 },
  "CONTAMINA": { km: 32 },
  "COSUENDA": { km: 56 },
  "CUBEL": { km: 43 },
  "DAROCA": { km: 40 },
  "DEZA": { km: 55 },
  "EJEA DE LOS CABALLEROS": { km: 130 },
  "EL FRASNO": { km: 20 },
  "EMBID DE ARIZA": { km: 46 },
  "EMBID DE LA RIBERA": { km: 20 },
  "ENCINA CORBA": { km: 69 },
  "EPILA": { km: 55 },
  "FUENDETODOS": { km: 85 },
  "FUENTELSAZ": { km: 52 },
  "FUENTES DE JILOCA": { km: 18 },
  "GALLOCANTA": { km: 65 },
  "GALLUR": { km: 95 },
  "GELSA": { km: 138 },
  "GODOJOS": { km: 36 },
  "GOMARA": { km: 65 },
  "GOTOR": { km: 45 },
  "HUERMEDA": { km: 7.5 },
  "HUESCA": { km: 160 },
  "IBDES": { km: 34 },
  "ILLUECA": { km: 43 },
  "INOGES": { km: 27 },
  "JARABA": { km: 43 },
  "JARQUE": { km: 50 },
  "LA ALMUNIA": { km: 38 },
  "LA VILUENA": { km: 18 },
  "LAS TRUCHAS": { km: 29 },
  "LERIDA": { km: 235 },
  "LLUMES": { km: 40 },
  "LOGRONO": { km: 200 },
  "MADRID": { km: 245 },
  "MAGALLON": { km: 79 },
  "MALANQUILLA": { km: 40 },
  "MALLEN": { km: 94 },
  "MALUENDA": { km: 9 },
  "MANCHONES": { km: 37 },
  "MARA": { km: 16 },
  "MEDINACELI": { km: 87 },
  "MEQUINENZA": { km: 215 },
  "MESONES": { km: 44 },
  "MIEDES": { km: 20 },
  "MILMARCOS": { km: 50 },
  "MOLINA DE ARAGON": { km: 80 },
  "MONASTERIO DE PIEDRA": { km: 30 },
  "MONREAL DE ARIZA": { km: 50 },
  "MONTEAGUDO": { km: 55 },
  "MONTERDE": { km: 30 },
  "MONTON": { km: 22 },
  "MONZON": { km: 235 },
  "MORATA DE JALON": { km: 27 },
  "MORATA DE JILOCA": { km: 15 },
  "MORES": { km: 33 },
  "MOROS": { km: 25 },
  "MUELA (LA)": { km: 66 },
  "MUNEBREGA": { km: 15 },
  "MURERO": { km: 32 },
  "NOMBREVILLA": { km: 47 },
  "NUEVALOS": { km: 27 },
  "OLVES": { km: 16 },
  "OLVEGA": { km: 90 },
  "ORERA": { km: 20 },
  "PAMPLONA": { km: 220 },
  "PARACUELLOS DE JILOCA": { km: 5 },
  "PARACUELLOS DE RIBERA": { km: 25 },
  "PINA DE EBRO": { km: 120 },
  "PURROY": { km: 38 },
  "RICLA": { km: 40 },
  "RUESCA": { km: 55 },
  "SABINAN": { km: 30 },
  "SABINANIGO": { km: 220 },
  "SAN SEBASTIAN": { km: 310 },
  "SANTA CRUZ DE GRIO": { km: 33 },
  "SANTANDER": { km: 410 },
  "SEDILES": { km: 12.5 },
  "SESTRICA": { km: 35 },
  "SIGUENZA": { km: 120 },
  "SISAMON": { km: 50 },
  "SORIA": { km: 95 },
  "TARAZONA": { km: 110 },
  "TERRER": { km: 7.5 },
  "TERUEL": { km: 140 },
  "TIERGA": { km: 48 },
  "TOBED": { km: 38 },
  "TORRALBA D LOS FRAILES": { km: 52 },
  "TORRALBA DE RIBOTA": { km: 13 },
  "TORRELAPAJA": { km: 43 },
  "TORRES": { km: 10 },
  "TORRIJO DE CANADA": { km: 35 },
  "TRASOBARES": { km: 60 },
  "TUDELA": { km: 110 },
  "UNCASTILLO": { km: 162 },
  "USED": { km: 45 },
  "VALENCIA": { km: 300 },
  "VALTORRES": { km: 16 },
  "VELILLA DE JILOCA": { km: 11 },
  "VERA DEL MONCAYO": { km: 99 },
  "VILLAFELICHE": { km: 24 },
  "VILLALBA DE PEREJILES": { km: 11 },
  "VILLALENGUA": { km: 30 },
  "VILLARROYA D LA SIERRA": { km: 22 },
  "VILLEL DE MESA": { km: 66 },
  "ZARAGOZA": { km: 90 },
};

export const DISPLAY_NAMES: Record<string, string> = {
  "AGREDA": "Ágreda",
  "AINZON": "Ainzón",
  "ALAGON": "Alagón",
  "ALCALA DEL MONCAYO": "Alcalá del Moncayo",
  "ALCANIZ": "Alcañiz",
  "ALFAJARIN": "Alfajarín",
  "ALHAMA DE ARAGON": "Alhama de Aragón",
  "ALMAZAN": "Almazán",
  "ALMONACID DE LA SIERRA": "Almonacid de la Sierra",
  "ALDEHUELA DE LIESTOS": "Aldehuela de Liestos",
  "ANINON": "Aniñón",
  "ARANDIGA": "Arándiga",
  "ARCOS DE JALON": "Arcos de Jalón",
  "BREA DE ARAGON": "Brea de Aragón",
  "BURBAGUENA": "Burbáguena",
  "CABOLAFUENTE": "Cabolafuente",
  "CARINENA": "Cariñena",
  "CASTEJON DE ALARBA": "Castejón de Alarba",
  "CASTEJON DE LAS ARMAS": "Castejón de las Armas",
  "CERVERA DE LA CANADA": "Cervera de la Cañada",
  "EPILA": "Épila",
  "LA ALMUNIA": "La Almunia",
  "LA VILUENA": "La Vilueña",
  "LOGRONO": "Logroño",
  "MAGALLON": "Magallón",
  "MALLEN": "Mallén",
  "MOLINA DE ARAGON": "Molina de Aragón",
  "MONTON": "Montón",
  "MONZON": "Monzón",
  "MORATA DE JALON": "Morata de Jalón",
  "MUELA (LA)": "La Muela",
  "MUNEBREGA": "Munébrega",
  "NUEVALOS": "Nuévalos",
  "OLVEGA": "Ólvega",
  "SABINAN": "Sabiñán",
  "SABINANIGO": "Sabiñánigo",
  "SAN SEBASTIAN": "San Sebastián",
  "SIGUENZA": "Sigüenza",
  "SISAMON": "Sisamón",
  "TORRALBA D LOS FRAILES": "Torralba de los Frailes",
  "TORRIJO DE CANADA": "Torrijo de Cañada",
  "VILLARROYA D LA SIERRA": "Villarroya de la Sierra",
};

export const SERVICES = [
  {
    title: "Monasterio de Piedra",
    text: "Traslado directo desde Calatayud al parque natural, con recogida programada para la vuelta.",
    detail: "Ideal para visitantes que llegan en tren o se alojan en Calatayud y quieren aprovechar el día sin aparcar ni depender de horarios.",
  },
  {
    title: "Balnearios termales",
    text: "Alhama de Aragón, Jaraba, Paracuellos de Jiloca y complejos termales de la comarca.",
    detail: "Recogidas en domicilio, estación u hotel. Servicio cómodo para estancias de descanso, tratamientos y escapadas.",
  },
  {
    title: "Zaragoza y aeropuerto",
    text: "Estacion Delicias, Aeropuerto de Zaragoza, hospitales, centro y cualquier punto de la ciudad.",
    detail: "Viaje puerta a puerta para trenes, vuelos, citas médicas, gestiones o compras sin transbordos.",
  },
  {
    title: "Estaciones y tren",
    text: "Conexiones con la estación de Calatayud, Delicias y otros puntos de recogida.",
    detail: "Reserva con hora cerrada para llegar tranquilo, incluso en trayectos de madrugada o festivos.",
  },
  {
    title: "Rutas turísticas",
    text: "Arte mudéjar, Augusta Bilbilis, bodegas D.O. Calatayud y recorridos por la comarca.",
    detail: "Disponibilidad por horas para hacer varias paradas y adaptar el itinerario a tu ritmo.",
  },
  {
    title: "Traslados médicos",
    text: "Centros de salud, clínicas y hospitales de Calatayud y Zaragoza.",
    detail: "Servicio discreto y puntual, con posibilidad de coordinar la vuelta después de la cita.",
  },
  {
    title: "Empresas y eventos",
    text: "Reuniones, hoteles, proveedores, bodas, comuniones y celebraciones.",
    detail: "Reservas programadas para clientes, trabajadores o invitados con hasta 4 pasajeros.",
  },
  {
    title: "Pueblos de la comarca",
    text: "Ateca, Maluenda, Ariza, Daroca, Cetina, Miedes y muchos otros destinos.",
    detail: "Consulta el destino en la calculadora o en la tabla para ver un precio orientativo.",
  },
];

export const HOLIDAYS_2026 = new Set([
  "2026-01-01",
  "2026-01-06",
  "2026-04-02",
  "2026-04-03",
  "2026-04-23",
  "2026-05-01",
  "2026-06-01",
  "2026-08-15",
  "2026-09-08",
  "2026-10-12",
  "2026-11-02",
  "2026-12-07",
  "2026-12-08",
  "2026-12-25",
]);

export const FIXED_HOLIDAYS_MMDD = new Set([
  "01-01",
  "01-06",
  "04-23",
  "05-01",
  "06-01",
  "08-15",
  "09-08",
  "10-12",
  "11-01",
  "12-06",
  "12-08",
  "12-25",
]);
